name = "onetv"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Environment variables
[vars]
NEXT_PUBLIC_STORAGE_TYPE = "cloudflare-kv"

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "90d1e4f39ef64a0b97f960cac9cb1a12"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "OneTV"
database_id = "8b340e86-5212-45c7-b2b0-040a285d3104"
